ouster_driver:
  ros__parameters:
    lidar_ip: 192.168.254.2
    computer_ip: ""
    lidar_mode: "1024x10"
    imu_port: 7503
    lidar_port: 7502
    sensor_frame: laser_sensor_frame
    #sensor_frame: base_link
    laser_frame: laser_sensor_frame
    imu_frame: laser_sensor_frame

    # if False, data are published with sensor data QoS. This is preferrable
    # for production but default QoS is needed for rosbag.
    # See: https://github.com/ros2/rosbag2/issues/125
    use_system_default_qos: True

    # Set the method used to timestamp measurements.
    # Valid modes are:
    #
    #   TIME_FROM_INTERNAL_OSC
    #   TIME_FROM_SYNC_PULSE_IN
    #   TIME_FROM_PTP_1588
    #   TIME_FROM_ROS_RECEPTION
    #
    # (See this project's README and/or the Ouster Software Guide for more
    # information).
    #
    timestamp_mode: TIME_FROM_ROS_RECEPTION

    # Mask-like-string used to define the data processors that should be
    # activated upon startup of the driver. This will determine the topics
    # that are available for client applications to consume. The defacto
    # reference for these values are defined in:
    # `include/ros2_ouster/processors/processor_factories.hpp`
    #
    # For convenience, the available data processors are:
    #
    # IMG   - Provides 8-bit image topics suitable for ML applications encoding
    #         the range, ambient and intensity data from a scan
    # PCL   - Provides a point cloud encoding of a LiDAR scan
    # IMU   - Provides a data stream from the LiDARs integral IMU
    # SCAN  - Provides a synthesized 2D LaserScan from the 3D LiDAR data
    #
    # To construct a valid string for this parameter join the tokens from above
    # (in any combination) with the pipe character. For example, valid strings
    # include (but are not limited to):
    #
    # IMG|PCL
    # IMG|PCL|IMU|SCAN
    # PCL
    #
    proc_mask: PCL|IMU
    box_filter:
      enable: true
      # Stolzenberg 0
#      dimensions: [2.20, 1.00, 2.0] # x, y, z [meters]
#      translation: [-1.1, 0.0, 0.78] # x, y, z [meters]

      # Columbus 2
#      dimensions: [2.4, 0.7, 2.0] # x, y, z [meters]
#      translation: [-1.2, 0.0, 1.70] # x, y, z [meters]

      # Stolzenberg New
      dimensions: 
        x: 2.4
        y: 0.8
        z: 2.0
      translation:
        x: -1.2
        y: 0.0
        z: 1.20
